import React from 'react'
import {Container} from 'react-bootstrap'

const Placeholder = () =>(
    <Container>
    <div>
        <h2>Lorem Ipsum</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tincidunt mi venenatis elementum laoreet. Vivamus porttitor ante turpis, eget convallis odio vulputate at. Cras quis justo sit amet felis rutrum sagittis. Nullam a quam condimentum, placerat massa id, consectetur elit. Nulla ultricies nisl vel ligula dignissim malesuada. Curabitur imperdiet, metus ac pulvinar ultricies, dui est condimentum orci, ac tempus velit ipsum in dui. Nam lorem erat, posuere et lectus rhoncus, facilisis rhoncus nulla. Integer facilisis ornare orci, nec interdum odio faucibus eu. Vestibulum pharetra elementum elit, quis placerat arcu egestas sed. </p>
        <p>Sed nec sem nisl. Sed accumsan diam ut arcu viverra accumsan. In et massa at augue vulputate lacinia. Nunc tempor massa at mauris rutrum vestibulum ut in ipsum. Mauris gravida vulputate quam, non rutrum est egestas non. Nullam eu justo fermentum, imperdiet est suscipit, consectetur diam. Suspendisse sit amet venenatis massa, eu convallis dolor. Donec mollis odio dolor, at gravida sem dictum molestie. Morbi et fringilla dui. Pellentesque placerat arcu sed orci eleifend gravida. Nullam ac faucibus quam. Donec tempor tellus in tristique ullamcorper. Fusce condimentum elit vel libero suscipit bibendum. </p>
        <p>Sed laoreet magna eu massa aliquam vestibulum. Pellentesque eget erat id elit iaculis vestibulum. Fusce convallis malesuada lorem, a faucibus arcu. In ultrices arcu sit amet felis accumsan, vel bibendum felis tempus. Vestibulum nec luctus risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus auctor ipsum facilisis mauris commodo, at eleifend magna euismod. </p>
        <p>Aliquam volutpat ante et nisi maximus dapibus. Mauris dignissim pharetra dui, et dignissim urna blandit nec. Vivamus imperdiet dapibus dui, vel luctus orci. Phasellus faucibus nisl tortor, ut viverra ligula bibendum eu. Ut vel nunc quis dui scelerisque sodales ac facilisis erat. Nulla vitae magna quis mauris ornare bibendum id eget dolor. Aenean posuere, enim in molestie mattis, arcu elit sollicitudin odio, sit amet ultricies dolor purus sed quam. Donec egestas justo turpis. Nullam rhoncus eget sem vel hendrerit. Nam sed tellus tortor. Mauris pharetra sit amet lorem sit amet porta. Quisque ultricies, ante ut fermentum pretium, ex tortor ornare purus, nec aliquam nunc ligula id felis. Fusce porttitor porttitor metus, a placerat magna laoreet eu. Mauris cursus placerat dui, ac lacinia dui elementum in. Vestibulum magna sapien, scelerisque quis leo nec, congue gravida dolor. </p>
        <p>Quisque bibendum nibh et rutrum vestibulum. Vestibulum bibendum quis lacus sed tempus. Donec dui mi, maximus at enim non, ultrices eleifend lacus. Etiam elementum enim et dui tincidunt maximus. Morbi faucibus, elit at mattis tincidunt, odio odio mollis ipsum, id vulputate est metus sit amet mi. Nam sagittis risus id viverra condimentum. Integer lacinia, tellus ac euismod ullamcorper, lorem mauris sodales nibh, in semper sapien mi vitae odio. Nulla non mattis nisi. Nunc ac accumsan mauris, id dignissim dolor. Vestibulum ligula augue, convallis at vestibulum ornare, dictum a elit. Vivamus sodales accumsan metus, in consectetur neque porta eget. Suspendisse commodo in nisl ac lobortis. Aliquam non neque vitae lacus iaculis molestie. Curabitur ut mauris elit. In vitae malesuada urna, a feugiat nisl. </p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tincidunt mi venenatis elementum laoreet. Vivamus porttitor ante turpis, eget convallis odio vulputate at. Cras quis justo sit amet felis rutrum sagittis. Nullam a quam condimentum, placerat massa id, consectetur elit. Nulla ultricies nisl vel ligula dignissim malesuada. Curabitur imperdiet, metus ac pulvinar ultricies, dui est condimentum orci, ac tempus velit ipsum in dui. Nam lorem erat, posuere et lectus rhoncus, facilisis rhoncus nulla. Integer facilisis ornare orci, nec interdum odio faucibus eu. Vestibulum pharetra elementum elit, quis placerat arcu egestas sed. </p>
        <p>Sed nec sem nisl. Sed accumsan diam ut arcu viverra accumsan. In et massa at augue vulputate lacinia. Nunc tempor massa at mauris rutrum vestibulum ut in ipsum. Mauris gravida vulputate quam, non rutrum est egestas non. Nullam eu justo fermentum, imperdiet est suscipit, consectetur diam. Suspendisse sit amet venenatis massa, eu convallis dolor. Donec mollis odio dolor, at gravida sem dictum molestie. Morbi et fringilla dui. Pellentesque placerat arcu sed orci eleifend gravida. Nullam ac faucibus quam. Donec tempor tellus in tristique ullamcorper. Fusce condimentum elit vel libero suscipit bibendum. </p>
        <p>Sed laoreet magna eu massa aliquam vestibulum. Pellentesque eget erat id elit iaculis vestibulum. Fusce convallis malesuada lorem, a faucibus arcu. In ultrices arcu sit amet felis accumsan, vel bibendum felis tempus. Vestibulum nec luctus risus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Phasellus auctor ipsum facilisis mauris commodo, at eleifend magna euismod. </p>
    </div>
    </Container>
)

export default Placeholder;